### ISSUE TITLE
[Design] chunkBy

### ISSUE THREAD

**Issue by dsyme** [fsharp/FSharpLangDesign#25]
This is an adhoc location for a recorded discussion of adding  "chunkBy" to Seq/Array/List modules in F# 4.0 - See 

* the fslang.uservoice discussion at https://fslang.uservoice.com/forums/245727-f-language/suggestions/6402339-add-chunkby-and-countgroupsby-functions-to-seq 

* the overall proposed collection library normalization and additions at https://github.com/fsharp/FSharpLangDesign/blob/master/CoreLibraryFunctions.md

Signatures:

Seq.chunkBy : ('T -> 'Key) -> seq<'T> -> seq<seq<'Key * 'T>>
List.chunkBy : ('T -> 'Key) -> 'T list -> ('Key * 'T list) list
Array.chunkBy : ('T -> 'Key) -> 'T[] -> ('Key * 'T[]) []

where elements are repeatedly collected into one chunk until the key changes, left to right.  This has been a commonly requested function.

An implementation would of course be needed, with performance checks.

Please use this thread to discuss, e.g.

* comment on proposed name

* would we need "countChunksBy"?

* send links to equivalent functions in other data programming libraries

**Comment by PatrickMcDonald** [comment]
It was suggested to me to look at implementing `chunkBy` and `DivideBy`, where

`chunkBy: n:int -> seq<'T> -> seq<seq<'T>>` divides a list into chunks of at most n items

`divideBy: n:int -> seq<'T> -> seq<seq<'T>>` divides a list into at most n chunks

I called these functions `chunksOf` and `divideInto`, leaving it open to implement `chunkBy` as originally suggested at a future date.

I also went with the signatures above rather than, like was done in `windowed`, `int -> seq<'T> -> seq<'T []>`

See Microsoft/visualfsharp#261

**Comment by enricosada** [comment]
@dsyme that's got merged, the issues should be closed

**Comment by dsyme** [comment]
correct, thanks

**Comment by gmpl** [comment]
@enricosada What got merged?

There's no ``chunkBy`` anywhere in F# Core.
This is confusing, what got merged is ``chunkBySize``, but the initial discussion was about ``chunkBy`` with the signatures proposed by @dsyme  in the first comment of this discussion.

Since the RFC for F# 4.1 is already closed this should be re-opened (as it was approved in the user voice) and planned for F# vNext.

**Comment by tye-travcomuk** [comment]
Is there any update on including `chunkBy` in  F# Core?
I can not find any newer references to a `chunkBy` function or a function with the same purpose (lazily grouping elements based upon a key equality) rather than predetermined group sizes offered by `chunkBySize`.
