### ISSUE TITLE
[Design] Implement except on seq, array and list

### ISSUE THREAD

**Issue by PatrickMcDonald** [fsharp/FSharpLangDesign#41]
As suggested in [uservoice](http://fslang.uservoice.com/forums/245727-f-language/suggestions/7068430-add-except-function-to-core-collection-modules) we should implement `Except` on seq, array and list.

The initial PR is Microsoft/visualfsharp#253

Some decisions:

1. Should duplicates be removed from the result?  This is how Enumerable.Except works (it refers to it as a _Set Difference_)

2. Should the signature be `seq<'T> -> M('T) -> M('T)` rather than `M('T) -> M('T) -> M('T)` as suggested by @forki? Probably yes

3. If we're implementing Except, should we be also implementing Union and Intersection? These are also implemented in LINQ.  Should we also allow custom comparers?

**Comment by dsyme** [comment]
Hi @PatrickMcDonald  - Could you email me on donsyme AT fastmail DOT com?  I want to ask you about something else too (and I don't know your email :) )

thanks
don

**Comment by dsyme** [comment]
w.r.t. Except - yes, Union and Intersect should really be there too

- The Set module currently uses Set.difference for "Except", with the arguments reversed. M.except is better naming as it makes sense in a current setting " xs |> List.except [3;4;5]"

- The Set module also includes Set.unionMany and Set.intersectMany.

Getting a robust and efficient implementation of these primitives can be hard, because you need to switch to hash-table lookups at some point.  Naïve implementations over small collections obviously won't cut it.  LINQ may/should have been optimized well - at least over concrete collections - so will be the thing you need to look at for these cases.

**Comment by enricosada** [comment]
already merged, can be closed
